apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    name: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      port: 15444
      targetPort: 80
  type: LoadBalancer
